### PR TITLE
Adding support for multiple axis ( up to 2 ), axis on right, and log scale

### PR DESCRIPTION
**Pull request by shroffk**
This is added because of pressing needs at NSLS2... while we find a better long term supported plotting solution

image

### CODE REVIEW

**Comment by shroffk** [comment]
@kasemir ( sorry I could not add you as a reviewer )

**Comment by kasemir** [comment]
Bummer that you had to go into jquery.flot.logaxis.js since that would be clobbered if we update to a newer flot version.

**Comment by kasemir** [comment]
Are you  running this on tomcat 9 or older? For tomcat 10, we'd have to update some package imports because the API moved, #12

**Comment by shroffk** [comment]
Ya.. I was annoyed at the label formatter being hard coded.
but honestly the changes to the logaxis.js can be lived without

As I mentioned... after working on these changes I am convinced we need a more sustainable solution which should start with a new library

**Comment by shroffk** [comment]
> Are you running this on tomcat 9 or older? For tomcat 10, we'd have to update some package imports because the API moved, #12

currently I am running on tomcat 9.. but I will update to 10 soon... thanks for the reference

**Comment by kasemir** [comment]
I'm on older tomcat releases, and the changes are incompatible. Might mean we need to keep a "tomcat10" branch for a little while....

**Pull request merged**
