### PR TITLE
 Action Button : Open Display target value is not used #25

### PR DESCRIPTION
**Pull request by lcaouen**
Open new tab when target is New Tab or New Window

### CODE REVIEW

**Comment by kasemir** [comment]
Does that generally work, or do popup blockers and the like in most web browsers now block opening new windows, so the end user will see <nothing>?

**Comment by lcaouen** [comment]
I've tested on firefox / chrome / edge (chromium), it opens a new tab, no popup blocking

**Comment by lcaouen** [comment]
By the way, thanks for having accepted my PR

**Comment by kasemir** [comment]
>  it opens a new tab

Right, that's likely to always work. Opening a new window would be a problem.

For what it's worth, we really prefer the default of "replace" to minimize the number of open displays. With "tab" or "window", operators tend to end up with many open windows and next you get emails about the computer being slow.

The desktop version is thus just like a web browser: Opening a related display will by default replace the current display, unless you use a "Control-click" (Command-click on Mac) to open in a new tab. Making the target configurable as tab or window is a result of resigning to the fact that legacy displays supported those unfortunate options and now the choice is
a) Do I want to get emails from control system engineers who ask about those missing options
b) Should they then live with emails from their users about computers being slow as a result of all the open tabs/windows that use CPU

Ideally, the web runtime would also support "Control-click" (Command-click on Mac), but for now the action button only reacts to plain click...

**Comment by lcaouen** [comment]
Yes, you're right, "replace" should be the default.
I'm gonna have a look to the ctrl+clic too.
I will do the change today or begining of next week

**Pull request merged**
